cat:
	gcc -o fuzzer_cat test_cat.c ../src/fuzzer.c ../src/create_inp.c ../src/config.c

troff:
	gcc -o fuzzer_troff test_troff.c ../src/fuzzer.c ../src/create_inp.c ../src/config.c 

huns:
	gcc -o fuzzer_huns test_huns.c ../src/fuzzer.c ../src/create_inp.c ../src/config.c 

clean:
	rm -rf fuzzer_cat fuzzer_troff fuzzer_huns 