runner: ../runner_test.c ../runner.c ../runner.h
	gcc -o runner ../runner_test.c ../runner.c

print_runner: ../PrintRunner/print_runner.c ../PrintRunner/print_runner.h 
	gcc -o print_runner ../PrintRunner/print_runner.c ../runner.c
	
clean:
	rm -rf runner